platform: linux
inputs:
  - name: src
outputs:
  - name: src
run:
  dir: src
  path: bash
  args:
    - -c
    - |
      npm run generate:types
      npm install @img/sharp-linux-x64 --save-optional
      NEXT_TELEMETRY_DISABLED=1 npm run build
